apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: default
data:
  postgresPassword: U3Ryb25nUGFzc3dvcmQ= #StrongPassword
  password: QXBwUGFzc3dvcmQ= #AppPassword
