# define default database user, name, and password for PostgreSQL deployment
# parameters taken from https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart

image:
  tag: 14.5.0-debian-11-r3

commonLabels:
  app: shopping-database

auth:
  enablePostgresUser: true
  existingSecret: "postgres-secret"
  database: "shopping_db"
  username: "shopping_user"
  secretKeys:
    adminPasswordKey: "postgresPassword"
    userPasswordKey: "password"

# The postgres helm chart deployment will be using PVC postgresql-pv-claim
persistence:
  enabled: true
  existingClaim: "postgresql-pv-claim"